class { 'backuppc::server':
  wakeup_schedule              => [1, 2, 3, 4, 5, 21, 22, 23],
  max_backups                  => 2,
  max_user_backups             => 1,
  blackout_zero_files_is_fatal => false,
  backuppc_password            => 'test1234',
  max_pending_cmds             => 10,
  max_backup_pc_nightly_jobs   => 3,
  backup_pc_nightly_period     => 2,
  max_old_log_files            => 7,
  df_max_usage_pct             => 85,
  trash_clean_sleep_sec        => 500,
  dhcp_address_ranges          => [],
  full_period                  => '5.97',
  full_keep_cnt                => 2,
  full_age_max                 => 30,
  incr_period                  => '1.37',
  incr_keep_cnt                => 5,
  incr_age_max                 => 15,
  incr_levels                  => [1,2],
  incr_fill                    => true,
  partial_age_max              => 2,
  restore_info_keep_cnt        => 20,
  archive_info_keep_cnt        => 20,
  blackout_good_cnt            => 5,
  blackout_periods             => [
    {
      hourBegin =>  7.0,
      hourEnd   => 19.5,
      weekDays  => [1, 2, 3, 4, 5],
    },
    {
      hourBegin => 23,
      hourEnd   =>  5,
      weekDays  => [5, 6],
    },
  ],
  email_notify_min_days        => 1.5,
  email_from_user_name         => 'bpcreport',
  email_admin_user_name        => 'backuppc-alt',
  email_notify_old_backup_days => 7,
  apache_allow_from            => '127.0.0.1',
}
